--- #YAML:1.0
name:               XML-Handler-Dtd2Html
version:            0.42
abstract:           HTML documentation generator from a DTD
author:
    - Francois PERRAD (francois.perrad@gadz.org)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTML::Template:     0
    Parse::RecDescent:  0
    XML::Parser:        2.31
    XML::SAX:           0.11
    XML::SAX::Base:     1
    XML::SAX::Expat:    0.37
    XML::SAX::Writer:   0.44
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
