
all:
	dtd2html.pl -t "Perl Package Distribution" -o ppd sample.ppd

frame:
	mkdir frame
	dtd2html.pl -f -t "Perl Package Distribution" -o frame/ppd sample.ppd

book:
	mkdir book
	dtd2html.pl -b -t "Perl Package Distrubtion" -o book/ppd -s style -x sample.ppd sample.ppd

